const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {START,END,projection,unavailable}=require('./session-fixtures.cjs');
const html=fs.readFileSync(process.env.PROOF_HTML||path.join(__dirname,'..','index.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/)[1],helpers=source.slice(0,source.indexOf('  byId("auth-toggle").addEventListener'));
const NOW=Date.parse('2026-10-01T16:00:00Z');let clock=NOW;
class ClockDate extends Date {static now(){return clock;}}
const ctx={URLSearchParams,Intl,Date:ClockDate,location:{search:''},document:{body:{classList:{add(){}}}}};vm.createContext(ctx);vm.runInContext(helpers+'globalThis.helpers={nyTradingSession,nySessionContext,sessionMeasure,todayProfit,currentOpenPnl,accountCells};})();',ctx);const h=ctx.helpers;
const session=t=>JSON.parse(JSON.stringify(h.nyTradingSession(Date.parse(t))));
const context=t=>JSON.parse(JSON.stringify(h.nySessionContext(Date.parse(t))));
const account=()=>({id:'\u00b7\u00b7\u00b7123',linkOk:true,sessionMetrics:projection(NOW)});
const read=(a,kind='today',field='profit',now=NOW)=>h.sessionMeasure(a,kind,field,now);
const clone=x=>structuredClone(x);
test('NY17-18 excluded for entries; closed session remains addressable for results',()=>{assert.equal(session('2026-10-01T20:59:59Z').date,'2026-10-01');assert.equal(session('2026-10-01T21:00:00Z'),null);assert.equal(session('2026-10-01T21:59:59Z'),null);assert.deepEqual(session('2026-10-01T22:00:00Z'),{date:'2026-10-02',previousDate:'2026-10-01'});assert.equal(context('2026-10-01T21:30:00Z').active,false);});
test('Independent normal and winter UTC boundaries',()=>{assert.equal(context('2026-10-01T16:00:00Z').today.startTs,START);assert.equal(context('2026-10-01T16:00:00Z').today.endTs,END);const w=context('2026-01-08T12:00:00Z').today;assert.equal(w.startTs,Date.parse('2026-01-07T23:00:00Z'));assert.equal(w.endTs,Date.parse('2026-01-08T22:00:00Z'));});
test('Year rollover and invalid clocks',()=>{assert.deepEqual(session('2027-01-01T00:00:00Z'),{date:'2027-01-01',previousDate:'2026-12-31'});for(const ts of [NaN,'2026-10-01',-1,Number.MAX_SAFE_INTEGER])assert.equal(h.nySessionContext(ts),null);});
test('Legacy fields and UTC totals never populate new session cells',()=>{assert.equal(h.todayProfit({todayProfit:123,netToday:234}),null);const cells=Object.fromEntries(h.accountCells({id:'\u00b7\u00b7\u00b7123',todayProfit:123,yesterdayProfit:456,testerAccountPnlDivergence:0,missedTesterTrades:0,previousTradingDays:[{profit:456}]}));for(const key of ["Today's Profit","Yesterday's Profit",'Tester vs. Account P&L divergence','Missed tester trades'])assert.equal(cells[key],'Unavailable');});
test('Verified projection renders exact profit, signed divergence and missed count',()=>{const a=account(),cells=Object.fromEntries(h.accountCells(a));assert.equal(read(a),40);assert.equal(read(a,'yesterday'),90);assert.equal(read(a,'comparison','pnlDivergence'),-10);assert.equal(read(a,'comparison','missedTesterTrades'),1);assert.equal(cells["Today's Profit"],'$40.00');assert.equal(cells["Yesterday's Profit"],'$90.00');assert.equal(cells['Missed tester trades'],'1');assert.match(cells['Tester vs. Account P&L divergence'],/10\.00/);});
test('Unknown contract,timezone,shape or raw proof cannot be rendered',()=>{for(const mutate of [m=>m.version='old',m=>m.timezone='UTC',m=>delete m.active,m=>m.active='true',m=>m.secret='PRIVATE',m=>m.today.proof={coverage:true},m=>m.today.profit='40']){const a=account();mutate(a.sessionMetrics);assert.equal(read(a),null);}const a=account();delete a.sessionMetrics.today;assert.equal(read(a),null);});
test('Missing/partial/unverified source coverage stays null without clearing complete sibling',()=>{for(const reason of ['missing_evidence','incomplete_coverage','unreviewed_evidence','generation_mismatch','quantity_mismatch','pending_entries']){const a=account();a.sessionMetrics.today=unavailable(a.sessionMetrics.today,false,reason);a.sessionMetrics.comparison=unavailable(a.sessionMetrics.comparison,true,reason);assert.equal(read(a),null);assert.equal(read(a,'comparison','missedTesterTrades'),null);assert.equal(read(a,'yesterday'),90);}});
test('Numeric zero is measured only with verified complete schema',()=>{const a=account();a.sessionMetrics.today.profit=0;a.sessionMetrics.comparison.pnlDivergence=0;a.sessionMetrics.comparison.missedTesterTrades=0;assert.equal(read(a),0);assert.equal(read(a,'comparison','missedTesterTrades'),0);a.sessionMetrics.comparison.state='unavailable';assert.equal(read(a,'comparison','missedTesterTrades'),null);});
test('Stale/future captures and wrong boundaries cannot acquire receipt freshness',()=>{for(const mutate of [b=>b.asOfTs=NOW-120001,b=>b.asOfTs=NOW+1,b=>b.date='2026-09-30',b=>b.startTs++,b=>b.endTs++,b=>b.asOfTs=START-1,b=>b.asOfTs='1']){const a=account();mutate(a.sessionMetrics.today);assert.equal(read(a),null);}assert.equal(read(account(),'today','profit',NOW+120000),40);assert.equal(read(account(),'today','profit',NOW+120001),null);assert.equal(read(account(),'comparison','missedTesterTrades',NOW+120001),null);assert.equal(read(account(),'yesterday','profit',NOW+120001),90);});
test('Invalid comparison pairing,counts and profits reject both measures',()=>{for(const mutate of [b=>b.pnlDivergence=null,b=>b.pnlDivergence=Infinity,b=>b.pnlDivergence=1e13,b=>b.missedTesterTrades=-1,b=>b.missedTesterTrades=0.5,b=>b.missedTesterTrades='0',b=>b.missedTesterTrades=100001]){const a=account();mutate(a.sessionMetrics.comparison);assert.equal(read(a,'comparison','pnlDivergence'),null);assert.equal(read(a,'comparison','missedTesterTrades'),null);}});
test('Current cash needs link; closed historical cash survives link loss',()=>{const a=account();a.linkOk=false;assert.equal(read(a),null);assert.equal(read(a,'yesterday'),90);});
test('17-18 break and18 rollover retain only exact complete close',()=>{const a=account();a.sessionMetrics=projection(END);assert.equal(read(a,'today','profit',END+1800000),40);assert.equal(read(a,'today','profit',END+3600000),null);assert.equal(read(a,'yesterday','profit',END+3600000),40);const partial=account();assert.equal(read(partial,'today','profit',END),null);assert.equal(read(partial,'yesterday','profit',END+3600000),null);});
test('Exact PR26 producer/Worker projection is consumable by frontend', {skip:!process.env.FTB_SESSION_MODULE_ROOT},async()=>{const {pathToFileURL}=require('node:url');const root=process.env.FTB_SESSION_MODULE_ROOT;const load=relative=>import(pathToFileURL(path.join(root,relative)).href);const [{sessionFixture,NOW:backendNow,ACCOUNT},{loadSessionEvidence,decorateSessionMetrics},{projectSessionMetrics}]=await Promise.all([load('publisher/fixtures/session.synthetic.mjs'),load('publisher/session_metrics.mjs'),load('worker/session.mjs')]);const bytes=Buffer.from(JSON.stringify(sessionFixture())),digest=require('node:crypto').createHash('sha256').update(bytes).digest('hex');const p={ts:backendNow,accounts:[clone(ACCOUNT)]};decorateSessionMetrics(p,loadSessionEvidence({path:'SYNTHETIC',expectedSha256:digest,read:()=>bytes}));const a={...ACCOUNT,sessionMetrics:projectSessionMetrics(p.accounts[0].sessionMetrics,backendNow,ACCOUNT)};assert.equal(read(a,'today','profit',backendNow),40);assert.equal(read(a,'comparison','pnlDivergence',backendNow),0);assert.equal(read(a,'comparison','missedTesterTrades',backendNow),1);});
test('Private/demo projection never supplies these public financial measures',()=>{const a=account();a.visibility='private';assert.equal(read(a),null);assert.equal(read(a,'yesterday'),null);assert.equal(read(a,'comparison','missedTesterTrades'),null);});
test('Weekend closure retains Friday and Thursday; Sunday18 opens Monday with Friday previous',()=>{
 for(const t of ['2026-10-02T21:00:00Z','2026-10-03T16:00:00Z','2026-10-04T21:59:59Z']){const c=context(t);assert.equal(c.active,false);assert.equal(c.today.date,'2026-10-02');assert.equal(c.yesterday.date,'2026-10-01');}
 for(const t of ['2026-10-04T22:00:00Z','2026-10-05T16:00:00Z'])assert.deepEqual(session(t),{date:'2026-10-05',previousDate:'2026-10-02'});
});
test('DST Sunday stays closed until18 and Monday uses correct seasonal offset',()=>{
 for(const [day,open,start,end] of [['2026-03-08','2026-03-08T22:00:00Z','2026-03-08T22:00:00Z','2026-03-09T21:00:00Z'],['2026-11-01','2026-11-01T23:00:00Z','2026-11-01T23:00:00Z','2026-11-02T22:00:00Z']]){
 assert.equal(session(day+'T12:00:00Z'),null);const c=context(open);assert.equal(c.today.startTs,Date.parse(start));assert.equal(c.today.endTs,Date.parse(end));assert.equal(c.today.endTs-c.today.startTs,23*3600000);
 }
});
test('Friday closed proof renders Monday Yesterday; legacy weekend blocks and missing data stay null',()=>{
 const now=Date.parse('2026-10-05T16:00:00Z'),c=h.nySessionContext(now),a=account();
 a.sessionMetrics.yesterday={...a.sessionMetrics.yesterday,...c.yesterday,asOfTs:c.yesterday.endTs};assert.equal(read(a,'yesterday','profit',now),90);
 a.sessionMetrics.yesterday.date='2026-10-04';assert.equal(read(a,'yesterday','profit',now),null);delete a.sessionMetrics;assert.equal(read(a,'today','profit',now),null);assert.equal(read(a,'yesterday','profit',now),null);
});
test('Selector matches reviewed backend across weekend and DST boundaries',{skip:!process.env.FTB_SESSION_MODULE_ROOT},async()=>{
 const {pathToFileURL}=require('node:url');const {sessionContext}=await import(pathToFileURL(path.join(process.env.FTB_SESSION_MODULE_ROOT,'worker/session.mjs')).href);
 for(const day of ['2026-03-08','2026-11-01','2026-10-02','2026-10-04','2026-10-05'])for(let hour=0;hour<24;hour++){const ts=Date.parse(day+'T00:00:00Z')+hour*3600000,expected=sessionContext(ts),actual=JSON.parse(JSON.stringify(h.nySessionContext(ts)));assert.deepEqual(actual,{active:expected.active,today:expected.today,yesterday:expected.yesterday});}
});
